/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;

/**
 *
 * @author billc
 */
public class GamePanel extends javax.swing.JPanel {

    /**
     * Creates new form GamePanel
     */
    int numPlayers = 0;
    int selectedMap = 0;
    SpacePanel space1;

    public GamePanel() {
         
        Object[] options1 = {"2 Player", "AI"};
        String selectedValue = (String) JOptionPane.showInputDialog(null,
                "2 Player or 1 Player vs AI?", "Select Gamemode",
                JOptionPane.QUESTION_MESSAGE, null,
                options1, options1[0]);

        switch (selectedValue) {
            case "2 Player":
                numPlayers = 2;
                break;
            case "AI":
                numPlayers = 1;
                break;

        }

        
        
        Object[] options2 = {"1 Star Fixed System", "2 Star Non-Fixed System", "3 Star Fixed System", "No Star System"};
        selectedValue = (String) JOptionPane.showInputDialog(null,
                "Select Map", "Select Map",
                JOptionPane.QUESTION_MESSAGE, null,
                options2, options2[0]);

        switch (selectedValue) {
            case "1 Star Fixed System":
                selectedMap = 1;
                break;
            case "2 Star Non-Fixed System":
                selectedMap = 2;
                break;
            case "3 Star Fixed System":
                selectedMap = 3;
                break;
            case "No Star System":
                selectedMap = 4;
                break;

        }
        space1 = new SpacePanel(numPlayers,selectedMap);
        this.add(space1);
         initComponents();

        this.validate();

      
        
        
        
        
        space1.timer();
        space1.t1.start();
        space1.setFocusable(true);
    }

    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pauseButton = new javax.swing.JButton();
        quitButton = new javax.swing.JButton();
        restartButton = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(600, 600));
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));

        pauseButton.setText("Pause");
        pauseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pauseButtonActionPerformed(evt);
            }
        });
        add(pauseButton);

        quitButton.setText("Quit to Main Menu");
        quitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitButtonActionPerformed(evt);
            }
        });
        add(quitButton);

        restartButton.setText("Restart");
        restartButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                restartButtonActionPerformed(evt);
            }
        });
        add(restartButton);
    }// </editor-fold>//GEN-END:initComponents

    private void pauseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pauseButtonActionPerformed
        // TODO add your handling code here:
        if (pauseButton.getText().equals("Pause")) {
            space1.updateBodies = false;
            pauseButton.setText("Resume");
        } else if (pauseButton.getText().equals("Resume")) {
            space1.updateBodies = true;
            pauseButton.setText("Pause");
        }
    }//GEN-LAST:event_pauseButtonActionPerformed

    private void quitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitButtonActionPerformed
        // TODO add your handling code here:
        MainFrame topFrame = (MainFrame) SwingUtilities.getWindowAncestor(this);
        topFrame.displayPanel(new MainMenuPanel(), "MAINMENU");
    }//GEN-LAST:event_quitButtonActionPerformed

    private void restartButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_restartButtonActionPerformed
        // TODO add your handling code here:
        MainFrame topFrame = (MainFrame) SwingUtilities.getWindowAncestor(this);
        topFrame.displayPanel(new GamePanel(), "GAME");
    }//GEN-LAST:event_restartButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton pauseButton;
    private javax.swing.JButton quitButton;
    private javax.swing.JButton restartButton;
    // End of variables declaration//GEN-END:variables
}
