/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;

/**
 *
 * @author billc
 */
public class GamePanel extends javax.swing.JPanel {

    /**
     * Creates new form GamePanel
     */
  
    int numPlayers=0;
    public GamePanel() {
         

        Object[] options ={"2 Player","AI"};
        String selectedValue = (String)JOptionPane.showInputDialog(null,
                "2 Player or 1 Player vs AI?", "Select Gamemode",
                JOptionPane.QUESTION_MESSAGE, null,
                options, options[0]);
        
        switch(selectedValue){
            case "2 Player":
                numPlayers=2;
                break;
            case "AI":
                numPlayers=1;
                break;
                
        }
        System.out.println(numPlayers);
        initComponents();
        space1.timer();
        space1.t1.start();
        space1.setFocusable(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        space1 = new GUI.SpacePanel(numPlayers);
        pauseButton = new javax.swing.JButton();
        quitButton = new javax.swing.JButton();
        restartButton = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(600, 600));
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));

        space1.setPreferredSize(new java.awt.Dimension(600, 600));

        javax.swing.GroupLayout space1Layout = new javax.swing.GroupLayout(space1);
        space1.setLayout(space1Layout);
        space1Layout.setHorizontalGroup(
            space1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        space1Layout.setVerticalGroup(
            space1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 612, Short.MAX_VALUE)
        );

        add(space1);

        pauseButton.setText("Pause");
        pauseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pauseButtonActionPerformed(evt);
            }
        });
        add(pauseButton);

        quitButton.setText("Quit to Main Menu");
        quitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitButtonActionPerformed(evt);
            }
        });
        add(quitButton);

        restartButton.setText("Restart");
        restartButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                restartButtonActionPerformed(evt);
            }
        });
        add(restartButton);
    }// </editor-fold>//GEN-END:initComponents

    private void pauseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pauseButtonActionPerformed
        // TODO add your handling code here:
        if (pauseButton.getText().equals("Pause")) {
            space1.updateBodies = false;
            pauseButton.setText("Resume");
        } else if (pauseButton.getText().equals("Resume")) {
            space1.updateBodies = true;
            pauseButton.setText("Pause");
        }
    }//GEN-LAST:event_pauseButtonActionPerformed

    private void quitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitButtonActionPerformed
        // TODO add your handling code here:
        MainFrame topFrame = (MainFrame) SwingUtilities.getWindowAncestor(this);
        topFrame.displayPanel(new MainMenuPanel(), "MAINMENU");
    }//GEN-LAST:event_quitButtonActionPerformed

    private void restartButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_restartButtonActionPerformed
        // TODO add your handling code here:
        MainFrame topFrame = (MainFrame) SwingUtilities.getWindowAncestor(this);
        topFrame.displayPanel(new GamePanel(), "GAME");
    }//GEN-LAST:event_restartButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton pauseButton;
    private javax.swing.JButton quitButton;
    private javax.swing.JButton restartButton;
    private GUI.SpacePanel space1;
    // End of variables declaration//GEN-END:variables
}
