/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import javax.swing.SwingUtilities;

/**
 *
 * @author billc
 */
public class TutorialPanel extends javax.swing.JPanel {

    /**
     * Creates new form TutorialPanel
     */
    public TutorialPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        quitTutorialButton = new javax.swing.JButton();

        quitTutorialButton.setText("Quit Tutorial");
        quitTutorialButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitTutorialButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(282, Short.MAX_VALUE)
                .addComponent(quitTutorialButton)
                .addGap(19, 19, 19))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(quitTutorialButton)
                .addContainerGap(254, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void quitTutorialButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitTutorialButtonActionPerformed
        // TODO add your handling code here:
        MainFrame topFrame = (MainFrame) SwingUtilities.getWindowAncestor(this);
        topFrame.displayPanel(new MainMenuPanel(), "MAINMENU");
    }//GEN-LAST:event_quitTutorialButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton quitTutorialButton;
    // End of variables declaration//GEN-END:variables
}
